### ISSUE TITLE
Can’t start (or restart) Outline service

### ISSUE THREAD

**Issue by xplosionmind** [YunoHost-Apps/outline_ynh#103]
### Describe the bug

The service named “Outline” fails and I can’t (re)start it.

### Context

- Hardware: VPS bought online
- YunoHost version: 11.2.0
- I have access to my server: Through SSH
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### Steps to reproduce

- Go to Tools > Services
- “outline” service has “failed” status, try to start it
- failure to start it

### Expected behavior

The “outline” service should be running nominally.

### [Logs](https://paste.yunohost.org/raw/fuloraduma)

**Comment by Limezy** [comment]
Sorry for the problem !
Could you please go to command line and run the below command : 
`sudo yunohost app setting outline language -v en_EN`
`cd /var/www/outline`
`sudo nano .env`
Then go to the bottom of the file and change the line
`DEFAULT_LANGUAGE=en`
To be 
`DEFAULT_LANGUAGE=en_EN`

**Comment by xplosionmind** [comment]
Fixed following [this process](https://github.com/YunoHost-Apps/outline_ynh/issues/103#issuecomment-1952691875).
Thank you!
