### ISSUE TITLE
Can I add Outline to the official Yunohost catalog ?

### ISSUE THREAD

**Issue by Limezy** [YunoHost-Apps/outline_ynh#23]
Upstream licence is Business Source License 1.1
https://github.com/outline/outline/blob/main/LICENSE
(Same licence as MariaDB)

It's not listed on SPDX as a free licence
https://spdx.org/licenses/BUSL-1.1.html

However, Yunohost seems to use MariaDB without any problem ?
I'm a bit lost here

(See https://github.com/YunoHost/apps/pull/1241#issuecomment-968557087)

**Comment by tituspijean** [comment]
No worries on that part, we voted in a recent contributors meeting to allow non-free apps back into the catalog. N8n was the app that restarted the discussion. We need to make the time to update the documentation and add a dedicated tag for it (as far as I remember), though. 😅

**Comment by Limezy** [comment]
That's great ! Indeed, would be a pitty not to have these very nice apps that don't have a real open source licence but that are anyway very close to the open source spirit (I know some would argue on that but I feel glad that we can perfectly legally offer apps as qualitative as N8n or Outline to the Yunohost community)

**Comment by alexAubin** [comment]
>No worries on that part, we voted in a recent contributors meeting to allow non-free apps back into the catalog

To clarify, I think the vote was about not-entirely-free-software (e.g. free software with some restriction) and we agreed to add them to the catalog upon review/validation of the license specificity, and if the license specificity is explicitly mentioned in some sort of disclaimer during install (but i may be mistaking, i don't remember the entire discussion)

In any case it sounds like this BUSL thingy could be okay (though i only had a super quick look at it)

Proposing to continue the discussion on https://github.com/YunoHost/apps/pull/1269
