### ISSUE TITLE
Make Outline_ynh compatible with ARM architecture

### ISSUE THREAD

**Issue by Limezy** [YunoHost-Apps/outline_ynh#50]

**Comment by navanchauhan** [comment]
Currently what is stopping the app to be packaged for ARM? I would love to contribute

**Comment by navanchauhan** [comment]
I was able to successfully install Outline on arm64 without making any changes

**Comment by Limezy** [comment]
Wow that's great ! Just seeing your messages now. I don't have any ARM to test.
Closing now
