### ISSUE TITLE
Configure email address used by outline?

### ISSUE THREAD

**Issue by mhfowler** [YunoHost-Apps/outline_ynh#65]
Currently my outline instance is using this email address to send emails: outline@outline.commoninternet.net

the way my yunohost is configured, these emails are not reaching their destination. I think on my yunohost only one email is able to send outgoing email properly (because it uses an smtp relay).

Is there anyway to configure what email address outline will use for sending emails?

**Comment by Limezy** [comment]
Hi, sure !
Just go to `/var/www/outline` and edit the file `.env` you will find there. 
You can edit the address you want on the line starting by : 
`SMTP_FROM_EMAIL= `
Then, à simple restart of outline service from the admin interface should do the trick. 

On my side I will have to double check if this .env file is updated or not during upgrade. Ideally it wouldn't, to allow custom choices like yours to survive outline upgrades.

**Comment by mhfowler** [comment]
Worked great, thanks so much!
