### ISSUE TITLE
Bug : Control characters in MinIO password manifest field

### ISSUE THREAD

**Issue by Gredin67** [YunoHost-Apps/outline_ynh#70]
At install I selected an existing yunohost user as admin for minIO. In the minIO admin password field I gave the same password as the yunohost user's one.
However I'm not able to connect to https://minio.arn-test.noho.st/login with this admin and password.
Did I do something wrong ?

**Comment by Gredin67** [comment]
I found the bug. At install I gave a password including a `+` which was replaced:
- ` ` with whitespace ` `  in  `MINIO_ROOT_PASSWORD`
- with `;` in `AWS_SECRET_ACCESS_KEY`

**Comment by Gredin67** [comment]
Also it was not clear to me if `minio_admin` should be an existing YunoHost user or if it will be a newly created system user or so?
Is it an issue if I user and existing YunoHost user ?

**Comment by Limezy** [comment]
Hi, the new release v0.72 gets rid of MinIO so your problems should now be solved !
Sorry for the very very late reply
